### PR TITLE
Message-Tag Extban

### PR DESCRIPTION
**Pull request by ValwareIRC**
This module adds a Group 4 extban allowing channel operators to +b/+e mtags per channel.

https://github.com/ValwareIRC/valware-unrealircd-mods/blob/main/mtag-extban/README.md

### CODE REVIEW

**Comment by syzop** [comment]
As mentioned on IRC, it would be better if we would provide more tools to do this for a module, rather than you having to resort to an command override which is always more risky.
Like, you do a find_channel on parv[1] but PRIVMSG can have multiple targets like `#one,#two,#three` in which case the lookup will fail and it will fallback to the normal command (override) calling, and thus the message tags making it through (evading the restriction).
And i also see a DelListItem but that just removes it from the list without freeing, so memory gets leaked, and if that would be fixed then i see m->next being touched but it would need to do like next = m->next and then the dellistitem/freeing/etc... etc.

I don't think it would be wise to allow it as-is. And, yeah, I think it would be better if we provide ways to do this in a module in UnrealIRCd so you don't have to go through hoops and shit.

**Comment by syzop** [comment]
I just looked quickly at our source and I see this in message.c:
```c
new_message(client, recv_mtags, &mtags);

RunHook(HOOKTYPE_PRE_CHANMSG, client, channel, mtags, text, sendtype);
```

It would be great if you could use HOOKTYPE_PRE_CHANMSG... it gives you client, channel and mtags, and you can freely delete mtags if you like, as next iteration (for like the second channel in a `#one,#two` scenario) would start fresh again with the original mtags.

Ok, the removal of tags seem a bit more complicated then, because you get passed MessageTag *mtags, and there can be situations where you need to delete the original head (mtags) and get a new head. Hmm. Interesting case :D. You would have to get a `MessageTag **mtags` (pointer to pointer) rather than `MessageTag *mtags` (pointer). That would mean we would have to change the prototype. I don't think the HOOKTYPE_PRE_CHANMSG is used lots though, so i think we could make that change.

**Comment by syzop** [comment]
I think with https://github.com/unrealircd/unrealircd/commit/89b2d91084501785a975c58f4bd48413294e3a4f you should be able to do that.
Use `HOOKTYPE_PRE_CHANMSG` and then you can do your filtering/stripping of mtags.

Be sure to actually free the message tag and iterate safely in the loop, like
```c
int my_pre_chanmsg(Client *client, Channel *channel, MessageTag **mtags, const char *text, SendType sendtype)
{
MessageTag *m_next;

for (m = *mtags; m; m = m_next)
{
        m_next = m->next;
        // -- add your logic of when to strip or not to strip here --
        if (get_rid_of_this_tag)
        {
                    DelListItem(m, *mtags);
                    safe_free(m->name);
                    safe_free(m->value);
                    safe_free(m);
        }
}
```

**Comment by ValwareIRC** [comment]
Thanks so much!

**Pull request closed without merging**
