### PR TITLE
Allows users to use KiwiIRC plugins to do stuff

### PR DESCRIPTION
**Pull request by ValwareIRC**
requested by ItsOnlyBinary, this module adds all existing kiwiirc-related mtags to unrealircd so that unrealircd users may make use of them.
Includes:
- file uploads
- conference
- tic tac toe

### CODE REVIEW

**Comment by Shillos** [comment]
I hope to see some +draft/react for KiwiIRC. That would be cool, or more IRCv3 stuff!

**Comment by syzop** [comment]
@ValwareIRC as mentioned on IRC, users can easily crash UnrealIRCd if this module is loaded on UnrealIRCd 6.0.6 and earlier because the message tag handlers in this module have no length restrictions and UnrealIRCd did not handle it properly. If you could set `min-unrealircd-version` to `6.0.7` then the PR can be approved. With UnrealIRCd 6.0.7 using the module won't lead to a crash.

Should anyone already use this module, then either upgrade to UnrealIRCd 6.0.7 immediately or temporarily disable this module.

The other 3rd party modules like `third/react` and `third/display-name` don't have this problem by the way because they have strict length checks. @Shillos that also answers your question, there is already a `third/react` module.

**Comment by syzop** [comment]
Oh, there is still another check in the code for total message (the entire line) at 4094. I thought we were obeying the 8k + 512 bytes by now (well 4k client tags + 4k server tags + 512 bytes irc) but I forgot there was another check somewhere else. It won't cause a crash but the message will be silently rejected with a warning message to be displayed to IRCOps telling an overflow was prevented. It's too late to fix that in 6.0.7 as it was already released. Also, it only impacts this module so a fix release sounds too much :D. And I need to carefully audit some code before bumping it after realizing there are some other buffer limits elsewhere in the code that all impact each other.

So I hope you can restrict the tags at say 1000 bytes each for now. Then next version (or some future git commit) it can be bumped to unlimited / 4k. To be honest I don't know if 4k is really needed at all, I mean the full 4k space for a fileupload tag or tic tac toe? But ah well... :D.

**Comment by ValwareIRC** [comment]
I've restricted the length of each to 3500 and allowed only one of these at a time; I see no reason a client would send more than one of these tags at a time, so this allows for longer tag values.

Edit: Required minimum UnrealIRCd version 6.0.7

**Pull request merged**
