### PR TITLE
Create channel-context.c

### PR DESCRIPTION
**Pull request by ValwareIRC**
[IRcv3 channel context](https://github.com/ircv3/ircv3-specifications/pull/498)

### CODE REVIEW

**Comment by syzop** [comment]
I think this would be OK to have in UnrealIRCd itself. Could you make a PR against unrealircd and drop this 3rd party module PR? It would then be `src/modules/channel-context.c`. Be sure to also update `Makefile.windows` and `src/modules/Makefile.in` accordingly.

It would be nice if the module would also check if the sending user is really in that channel. For this you can use `find_membership_link(client->user->channel, channel)`

**Comment by ValwareIRC** [comment]
Heya, I'm glad you would like it in the source, however regarding the check to see if a user is in the channel first - I think it's better to not have this check, I didn't add it in because of cases where, for example, a user messages a bot like ChanServ attempting to change a setting of their active channel, but the bot is not actually in that channel.

Arguably, when a channel is registered, usually either BotServ or ChanServ will reside in that channel, but there is the case where BotServ is in the channel but you are trying to modify something by messaging ChanServ directly.

I think therefore it should be down to the client to choose where to display such messages, and I think a context should be allowed, even if the client chooses to ignore it.

**Comment by syzop** [comment]
I'm fine with servers and ulines, of course. But I meant users, I don't think random users that aren't even in the channel should be able to clutter the screen of such a channel, that's just plain confusing. And since at UnrealIRCd we don't follow the classic IRCv3 approach of just letting everything through without caring, we can handle it at the server level.

**Comment by ValwareIRC** [comment]
Fantastic, works for me!

**Pull request closed without merging**
