### PR TITLE
LockServ; prohibit new connections to a particular server.

### PR DESCRIPTION
**Pull request by ValwareIRC**
https://github.com/ValwareIRC/valware-unrealircd-mods/blob/main/lockserv/README.md

### CODE REVIEW

**Comment by syzop** [comment]
I think you want to prevent people to connect, no?
Right now the user connects fully, gets a MOTD, etc, and then exits. That's because you use `HOOKTYPE_LOCAL_CONNECT`.
I suggest you use `HOOKTYPE_LOCAL_PRE_CONNECT` so you can reject the connection.
See https://www.unrealircd.org/api/6/group__HookAPI.html

**Comment by ValwareIRC** [comment]
hey good morning.

the reason I've done it this way is because it seemed the client in the `HOOKTYPE_LOCAL_PRE_CONNECT` hook was not yet marked as a User, and didn't seem to be able to distinguish a user client from a server client or RPC client, and the like.

please could you advise w/r/t this?

**Comment by syzop** [comment]
I suggest you change the hook type to:
`HookAdd(modinfo->handle, HOOKTYPE_PRE_LOCAL_CONNECT, 0, lockserv_connect);`

And then in `lockserv_connect` get rid of the IsUser check:
`if (IsServerLocked(client->uplink) && !find_tkl_exception(TKL_ZAP, client))`

Then things work as expected.

`HOOKTYPE_PRE_LOCAL_CONNECT` (and `HOOKTYPE_LOCAL_CONNECT`) are only called for users, never for servers or RPC, so the check can be scratched. The docs say this too:
_Called when a local user connects, allows pausing or rejecting the user (function prototype for HOOKTYPE_PRE_LOCAL_CONNECT)._

Furthermore, the check would fail because during pre local connect the current client->status is not `CLIENT_STATUS_USER` but still `CLIENT_STATUS_UNKNOWN`.

**Comment by ValwareIRC** [comment]
wow that was a quick response!

thanks very much for taking the time! =]

**Comment by syzop** [comment]
Other than that i saw no immediate crashes or issues with ASan, so that's good :)

**Pull request merged**
